[project]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
name = "sklearn-ecosystem"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
convert-to-notebooks = { cmd = "jupytext --to notebook ./python_files/*.py && mkdir -p ./notebooks && mv ./python_files/*.ipynb ./notebooks" }

[dependencies]
python = "~=3.11.0"
sqlite = "<3.49"

[pypi-dependencies]
ipython = "*"
ipykernel = "*"
jupyterlab = "*"
jupytext = "*"
rich = ">=13.9.4, <14"
ruff = ">=0.9.9, <0.10"
scikit-learn = ">=1.6.1, <2"
sentence-transformers = ">=3.4.1, <5"
plotly = ">=6.0.0, <7"
ipywidgets = ">=8.1.5, <9"
skore = ">=0.8.1, <1"
skrub = ">=0.5.1, <1"
skops = { git = "https://github.com/skops-dev/skops.git" }

